### ISSUE TITLE
Allow SSH Git URLs

### ISSUE THREAD

**Issue by Holt59** [isanae/mob#5]
As the title says ;)

I tried to do it by adding a `use_ssh` option, and it works for cloning (or the initial pull, don't really know how you do it). 

Then I noticed it did not work for `remote_XXX`, so I modified the `git` code to handle `remote_url` instead of org/name and then I noticed that `git_command` heavily rely on this so I gave up since that would break a lots of things.

**Comment by isanae** [comment]
Fixed in 94bd99f38df20332cd1b28c540f44093123f9b3b.
